config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  resources :agents

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :rates
  has_many :customers, :through => :rates
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :rates
  has_many :agents, :through => :rates
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :agent
  belongs_to :customer
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
  end
  def search
    @agents = Agent.page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/agents/index.html.slim
.container#main-container
  .row.bg_agents[style='margin-top:-20px']
    .row[style='margin-top:120px']
      .col-xs-offset-3.col-xs-6
        font[color='white']
          center
            h1 为您创造更好的职业生涯
    .row[style='margin:24px auto 224px auto']
      .col-xs-offset-3.col-xs-6
        .input-group
          input#address.form-control[type='text' placeholder='姓名，手机号码' required]
          span.input-group-btn
            button.btn.btn-success[type='button']
              = icon :search
  .row[style='margin-top:24px']
    .col-xs-3.text-center
      = icon 'comment-o', library: :font_awesome, class: 'fa-4x'
      h4.text-primary
        | 建立名声
      p.text-justify
        | 积攒声誉：带看房？买卖房？服务好？完事让客户在微信上点个赞呗，看的见的经验积少成多。
    .col-xs-3.text-center
      = icon 'line-chart', library: :font_awesome, class: 'fa-4x'
      h4.text-primary
        | 增加客源
      p.text-justify
        | 主动出击：还在店铺无所事事的值班吗？建立好自己的线上简介，让顾客主动找到勤快的你！
    .col-xs-3.text-center
      = icon :refresh, library: :font_awesome, class: 'fa-4x'
      h4.text-primary
        | 高转换率
      p.text-justify
        | 去伪存真： 看房客户有时也难辨真假，但是直接找经纪人的客户都是做好交易准备的！
    .col-xs-3.text-center
      = icon 'hand-spock-o', library: :font_awesome, class: 'fa-4x'
      h4.text-primary
        | 录单王
      p.text-justify
        | 躺着赚钱：YY一下...等你米尺网声誉够牛的那一天，顾客都会抢着找你录单...卖房子吗，别人卖吧...
  .row
    hr.devider
  .row.agents[style="margin-top:24px"]
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,w_320/v1/9344/10087809_1453100786.jpg.120x160_tjeswc.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 梁杰
      h5.text-primary
        | 链家 北京市 都市馨园店
      h5.bg-success
        | 销售王：107套成交历史
      h5.bg-info
        | 好评王：49条好评100%五星
      p.text-justify
        | 客户评价：“ 非常专业，之前在他这成交过房子，办理过程很好，很专业，所有注意事项和准备资料提前告知，流程很熟悉，帮助把控风险，整个过程很舒服值得托付买卖房子的事情。”
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,w_320/v1/9344/9370518ce8374a95ab22f5c1cf300923_155X209_idmyha.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 赵鸿飞
      h5.text-primary
        | 麦田 北京 当代家园店
      h5.bg-success
        | 销售王：75套成交历史
      h5.bg-info
        | 好评王：60条好评99%五星
      p.text-justify
        | 自我评价：“通过近5年的工作经验促成了不少买卖单量也让我获得了不少的荣誉和高评价与赞同。我会用我的真诚与用心，站在买卖双方的角度去考虑问题尽最大的能力去做到公平公正，不偏不向。大家挣得都是辛苦钱不容易，请相信我。”
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,w_320/v1/9344/20017170_1452412449.jpg.120x160_ute5f9.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 白雪
      h5.text-primary
        | 我爱我家：北京 十里堡店
      h5.bg-success
        | 销售王：125套成交历史
      h5.bg-info
        | 好评王：80条好评99%五星
      p.text-justify
        | 客户评价：“耐心，热心，全程陪同看房，服务周到！讲解详细，介绍清楚到位！”
  .row
    hr.devider

app/views/agents/search.html.slim
.container#main-container
  .panel.panel-default
    .panel-body
      .row
        ui.nav.nav-pills[style="display:inline-block"]
          li.disabled
            a[href="#" role="presentation"]
              b 区域：
          li.active
            a[href="#" role="presentation"]
              | 不限
          li
            a[href="#" role="presentation"]
              | 东城
          li
            a[href="#" role="presentation"]
              | 西城
          li
            a[href="#" role="presentation"]
              | 朝阳
          li
            a[href="#" role="presentation"]
              | 海淀
          li
            a[href="#" role="presentation"]
              | 丰台
          li
            a[href="#" role="presentation"]
              | 石景山
          li
            a[href="#" role="presentation"]
              | 通州
          li
            a[href="#" role="presentation"]
              | 昌平
          li
            a[href="#" role="presentation"]
              | 大兴
          li
            a[href="#" role="presentation"]
              | 亦庄
          li
            a[href="#" role="presentation"]
              | 顺义
          li
            a[href="#" role="presentation"]
              | 房山
          li
            a[href="#" role="presentation"]
              | 门头沟
          li
            a[href="#" role="presentation"]
              | 平谷
          li
            a[href="#" role="presentation"]
              | 怀柔
          li
            a[href="#" role="presentation"]
              | 密云
          li
            a[href="#" role="presentation"]
              | 延庆
          li
            a[href="#" role="presentation"]
              | 燕郊
      .row
        hr.devider
      .row
        ui.nav.nav-pills[style="display:inline-block"]
          li.disabled
            a[href="#" role="presentation"]
              b 排序：
          li.active
            a[href="#" role="presentation"]
              | 默认
          li
            a[href="#" role="presentation"]
              | 按好评度排序
          li
            a[href="#" role="presentation"]
              | 按成交量排序
          li
            a[href="#" role="presentation"]
              | 按看房率排序
  center.panel.panel-default
    .panel-body
      | 共有
      font[color='red']
        b = @agents.total_count
      | 名经纪人
      hr.devider
      - @agents.each do |agent|
        .row
          .col-xs-3
            = image_tag(agent.photo)
          .col-xs-2
            = agent.name
          .col-xs-2
            = agent.mobile
          .col-xs-2
            = agent.region
          .col-xs-3
            h1 = agent.score
        hr.devider
      = paginate @agents

app/views/layouts/agents.html.slim
doctype html
html
  head
    title
      | HOUSE.
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name='viewport' content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
  body
    = navbar position: :static do
      = vertical do
        = image_tag('brand.png', size:'160x50')
      = horizontal do
        = nav class: 'navbar-left' do
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
              | 选择城市
              span.caret
          ul.dropdown-menu
            li
              a[href="#"]
                | 北京
            li
              a[href="#"]
                | 上海
        = nav class: 'navbar-right' do
          = link_to '买卖/租赁', root_path
          = link_to '经纪人', agents_path
    = yield
    .container#footer-container
      footer
        p.pull-right
          | © 2016 北京三岔口信息技术有限公司
        p
          ul.list-inline
            li 关于我们
            li 联系我们
            li 加入我们
            li 隐私声明

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HOUSE.
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name='viewport' content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
  body
    = yield

app/views/layouts/site.html.slim
doctype html
html
  head
    title
      | HOUSE.
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name='viewport' content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
  body
    = navbar position: :static do
      = vertical do
        = image_tag('brand.png', size:'160x50')
      = horizontal do
        = nav class: 'navbar-left' do
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
              | 选择城市
              span.caret
          ul.dropdown-menu
            li
              a[href="#"]
                | 北京
            li
              a[href="#"]
                | 上海
        = nav class: 'navbar-right' do
          = link_to '买卖/租赁', root_path
          = link_to '经纪人', agents_path
    = yield
    .container#footer-container
      footer
        p.pull-right
          | © 2016 北京三岔口信息技术有限公司
        p
          ul.list-inline
            li 关于我们
            li 联系我们
            li 加入我们
            li 隐私声明

app/views/site/index.html.slim
.container#main-container
  .row.bg[style='margin-top:-20px']
    .row[style='margin-top:120px']
      .col-xs-offset-3.col-xs-6
        font[color='white']
          center
            h1 为您找到最优秀的经纪人
    .row[style='margin:24px auto 224px auto']
      .col-xs-offset-3.col-xs-6
        .input-group
          input#address.form-control[type='text' placeholder='区域，商圈，小区名称' required]
          span.input-group-btn
            button.btn.btn-success[type='button']
              = icon :search
  .row[style='margin-top:24px']
    .col-xs-4
      center
        .row[style='margin-bottom:12px']
          = image_tag('http://agentace.com/images/v2/components/how-find-the-best-agent.svg')
        .row
          h4 搜索
        .row
          | 输入想要买卖或租赁的房屋所在区域，商圈或小区名称
    .col-xs-4
      center
        .row[style='margin-bottom:12px']
          = image_tag('http://agentace.com/images/v2/components/how-agent-specialist-decision.svg')
        .row
          h4 匹配
        .row
          | 结合大数据与用户点评筛选出最优秀，最匹配的经纪人
    .col-xs-4
      center
        .row[style='margin-bottom:12px']
          = image_tag('http://agentace.com/images/v2/components/how-agent-specialist-introduction.svg')
        .row
          h4 服务
        .row
          | 为您提供经纪人的联系方式，让其为您提供最优质的服务
  .row
    hr.devider
  .row
    .row
      .col-xs-6
        .buyer
          .col-xs-offset-9.col-xs-3[style='padding-right:0;margin-top:24px']
            .text-center[style='padding:22px 0 22px 0; background-color:rgba(255,255,255,0.8)']
              h4[style='color:#2488c9'] 买家/租客
      .col-xs-6[style='background-color:#2488c9;height:360px']
        dl.text-center[style='color:white; line-height:24px; padding-top:46px']
          dt
            h4 更方便
          dd 优秀经纪人经验丰富，推荐最合适的房源，节省你宝贵的时间
          dt
            h4 更有效
          dd 优秀经纪人可以在交易过程中帮您看家，让您拿到更多实惠
          dt
            h4 更安全
          dd 我们不会泄露您的联系方式。交易的主动权掌握在您手上
    .row[style='margin-top:15px']
      .col-xs-6[style='height:360px']
        dl.text-center[style='color:#2488c9; line-height:24px; padding-top:46px']
          dt
            h4 更快捷
          dd 优秀经纪人可以显著缩短交易周期，优先推荐他们录入的房源
          dt
            h4 更精准
          dd 优秀经纪人可以更准确地为您定价，多卖5%-20%的价格
          dt
            h4 更省心
          dd 您与经纪人单点接触，一站式服务，避免不必要的骚扰
      .col-xs-6[style='padding-left:0;padding-right:0']
        .seller
          .col-xs-3[style='padding-left:0;margin-top:24px']
            .text-center[style='padding:22px 0 22px 0; background-color:#2488c9']
              h4[style='color:white'] 卖家/房东
    .row
      hr.devider
  .row.marketing[style="margin-top:24px"]
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,q_90,w_320/v1/9344/6ce25f384bac4901a236287d48eb3c80_lfgwyb.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 张雪琴
      h5.text-primary
        | 卖房：北京市 海淀区
      p.text-justify
        | 我家在华清嘉园有一套三居，想出手有一阵了。米尺网推荐了我爱我家的杨店长。杨店长在海淀这片有十几年的的买卖经验。杨店长认为我定价过于保守，在他的建议下我们把出售价多加了40万，因为现在是卖家市场。杨店长的店面重点主打我的户型，三周内就以非常理想的价格卖出了！”
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,w_320/v1/9344/u_3231927390_1752915971_fm_11_gp_0_y2uvwr.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 许天
      h5.text-primary
        | 买房：北京市 海淀区
      p.text-justify
        | “我一直想买一套魏公村附近的房子，因为孩子马上就要在附近上初中。在网上找了好几个月，但是到处都是假房源，所以效率很低。米尺网推荐了链家魏公村店的小王。一有什么好的房源，小王就会用微信第一时间跟进。终于在一个月后我们买到了称心的两室。感谢小王，感谢米尺网！”
    .col-xs-4.text-center
      = image_tag('http://res.cloudinary.com/hrscywv4p/image/upload/c_fill,f_auto,g_faces:center,h_320,q_90,w_320/v1/9344/Img423785208_foh5cj.jpg', class:'img-circle', size:'288x288')
      h4.text-muted
        | 白雪
      h5.text-primary
        | 租房：北京市 朝阳区
      p.text-justify
        | “最近刚搬来望京，在外企上班，平常很忙，没时间找房。在网上看了一些房子，但也只能零零星星地晚上下班去看，很没效率。米尺网推荐了麦田的胡月小姐。在我们电话沟通后，她一个周六就带我看了8套房子。我第二天就跟房东签约了。省了我不少时间！”
  .row
    hr.devider